AWSTemplateFormatVersion: '2010-09-09'

Transform: 'AWS::Serverless-2016-10-31'

Parameters:

  Bucket:
    Type: String
    Description: Bucket with the Java artifact
    ConstraintDescription: must be an existing bucket.

Resources:

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: live
      Variables:
        ServerlessExpressLambdaFunctionName: !Ref Function

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*

  LambdaApiGatewayExecutionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt Function.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Join
        - ''
        - - 'arn:aws:execute-api:'
          - !Ref AWS::Region
          - ":"
          - !Ref AWS::AccountId
          - ":"
          - !Ref ApiGateway
          - "/*/*"

  Function:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: com.jcastellanospinzon.jconfco2019.serverlessawshelloworld.Handler
      Runtime: java8
      CodeUri:
        Bucket: !Ref Bucket
        Key: "serverless-aws-helloworld-1.0.0.jar"
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 30
      Events:
        ProxyApiRoot:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /
            Method: ANY

Outputs:
  LambdaFunctionConsoleUrl:
    Description: Console URL for the Lambda Function.
    Value: !Join
      - ''
      - - https://
        - !Ref AWS::Region
        - ".console.aws.amazon.com/lambda/home?region="
        - !Ref AWS::Region
        - "#/functions/"
        - !Ref Function
  ApiGatewayApiConsoleUrl:
    Description: Console URL for the API Gateway API's Stage.
    Value: !Join
      - ''
      - - https://
        - !Ref AWS::Region
        - ".console.aws.amazon.com/apigateway/home?region="
        - !Ref AWS::Region
        - "#/apis/"
        - !Ref ApiGateway
        - "/stages/live"

  ApiUrl:
    Description: Invoke URL for your API. Clicking this link will perform a GET request on the root resource of your API.
    Value: !Join
      - ''
      - - https://
        - !Ref ApiGateway
        - ".execute-api."
        - !Ref AWS::Region
        - ".amazonaws.com/live/"
